data:
  raw: "../data/raw/"
  cleaned: "../data/cleaned/"
src: "../src"

images: "../images/"
  
transformers: "../transformers/"
scalers: "../scalers/"
encoders: "../encoders/"
models: "../models/"

x-y-split:
  test_size: 0.3
  random_state: 87


cv: 5
n_jobs: 32
random_state: 87
verbose: 1000

knn:
    n_neighbors: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    p: [1,2,3]
    weights : ["uniform","distance"]
       
random_forest:
 'max_depth': [3,5,10]
 'n_estimators': [10, 50, 100, 150]
 'criterion': ["squared_error", "absolute_error", "friedman_mse", "poisson"]
 'min_samples_split': [2,5,10]
 'max_features': ['auto', "sqrt", "log2"]
 'min_samples_leaf': [2,5,10]

gradient_boosting:
 'loss': ["squared_error", "absolute_error", "huber", "quantile"]
 'max_depth': [3,5,10]
 'n_estimators': [10, 50, 100, 150]
 'max_features': ['auto', "sqrt", "log2"]
 'criterion': ["squared_error", "friedman_mse"]
 'min_samples_split': [2,5,10]
 'min_samples_leaf': [2,5,10]     
        
        